numtide/devshell

mkDevShell/options.nix
=> Shorten the menu command

devshell.toml, docs/devshell.toml, docs/devshell.toml.md, mkDevShell/options.nix
=> Add command categories

mkDevShell/default.nix
The bash-completions package automatically finds the right completion scripts by
looking into XDG_DATA_DIRS. Probably other programs respecting XDG specs
can also benefit from setting that environment variable.
Thanks to https://github.com/NixOS/nixpkgs/pull/103501 for finding that
gem.
=> support for bash-completions

modules/back-compat.nix, modules/devshell.nix
The new startup sequence allows third-party modules to inject themselves
into the startup sequence.
[devshell.startup.myscript]
text = """
echo My script
"""
The interface is not public yet as it's not 100% settled yet.
=> modules: better control the startup sequence

devshell.toml, modules/commands.nix, modules/devshell.nix
This allows to just set the package to get it added to the list. Eg:
[[commands]]
package = "nixpkgs-fmt"
And get back this in the help menu:
nixpkgs-fmt - Nix code formatter for nixpkgs
Fixes #57
=> commands: use the package for name and help defaults

modules/git-hooks.nix, modules/modules.nix
/cc @blaggacao 
Example usage:
```toml
[git.hooks]
enable = true
[git.hooks.pre-commit]
text = """
#!/usr/bin/env bash
echo "Do something on pre-commit"
"""
```
The hooks are installed in the user's `.git/hooks` folder if any of those are set. The operation is idempotent for each hook and automatically cleans old hooks if they are symlinks to the /nix/store and the hook is undefined.
There is a little wrapper script that makes sure that the hooks only execute if the devshell environment has been loaded and revert to a warning otherwise. This allows users to switch branches and keep working even if the devshell is temporarily broken (yet, it can happen :))
=> modules: introduce git.hooks

modules/commands.nix, nix/writeDefaultShellScript.nix, tests/commands.nix, tests/default.nix
Not everybody wants to write Bash code.
Fixes #65
=> commands: allow to write non-bash scripts

modules/devshell.nix
Fixes https://github.com/numtide/devshell/commit/1c16db26875a9cf7f207be3f541fefe8c6574a4a#r47004053 and https://github.com/numtide/devshell/commit/1c16db26875a9cf7f207be3f541fefe8c6574a4a#r47004028
/cc @Mic92
=> devshell.env: add examples

devshell.toml, modules/back-compat.nix, modules/devshell.nix, modules/env.nix, modules/modules.nix, tests/default.nix, tests/devshell.nix, tests/env.nix
Sorry! devshell is not stable yet.
[[devshell.env]] was really a mouthful so it got moved in place of
[env].
Instead of:
[env]
FOO = "bar"
BAR = "baz"
Use:
[[env]]
name = "FOO"
value = "bar"
[[env]]
name = "BAR"
value = "baz"
=> break back-compat: [[env]]

default.nix, docs/SUMMARY.md, docs/default.nix, docs/extending.md, docs/getting_started.md, modules_extra/locale.nix
Introduces extra modules that can be loaded on-demand. This is to
avoid long evaluation times as the list of modules grow.
Whenever a module is prefixed with `extra.` in the docs, it can be
loaded by putting `import = ["extra.<name>"]` at the top of the
devshell.toml.
=> modules: introduce extra modules

nix/writeDefaultShellScript.nix
In [`writeDefaultShellScript.nix`](https://github.com/numtide/devshell/blob/ff6cffba08600f5b7b43f398fcb58bef023bc4c4/nix/writeDefaultShellScript.nix#L15), the `script` variable provides a default shebang if none is given in the passed `text` parameter, but `script` never actually gets passed to `writeTextFile` and the (unpatched) `text` is passed instead! Fixed that to pass `script`.
Additionally, fixed the call to `lib.hasPrefix`.
=> Fix writeDefaultShellScript to actually include default shebang

modules/default.nix
=> imp: keep access `extraModulesPath` encapsulated in the module system

nix/mkNakedShell.nix
It's the first variable unset on that line, no need to unset it twice 😃
=> Remove duplicated unset of NIX_BUILD_TOP

.envrc, .github/workflows/nix.yml, modules/devshell.nix, nix/mkNakedShell.nix, tests/core/commands.nix, tests/core/devshell.nix, tests/core/env.nix, tests/extra/git.hooks.nix, tests/extra/language.c.nix, tests/extra/language.rust.nix, tests/extra/locale.nix
Split the entrypoint and env.bash. This makes it easier to expose the
buildEnv.
=> all-in-one: merge entrypoint into the devshell dir

.github/workflows/nix.yml, README.md, extra/service/postgres.nix, modules/devshell.nix, modules/env.nix, tests/core/devshell.nix, tests/core/env.nix, tests/default.nix, tests/extra/service.postgres.nix
This is not a full service like nixos or home-manage services. But it puts in
place the base to be able to start the service.
Usage (devshell.toml):
```toml
imports = [ "service.postgres" ]
[service.postgres]
package = "postgres_12"
```
After entering the devshell, run `pg_ctrl start` to start the server.
=> introduce service.postgres

modules/devshell.nix, tests/core/devshell.nix
Fixes #26
Fixes #123
To get the old behaviour back, set `devshell.load_profiles` to
`true`.
Future improvements might be to explicitly list which profiles should be
loaded.
=> BREAKING: don't load etc/profile.d/*.sh by default

extra/git/hooks.nix
We don't want to rely on the fact that git is already in the PATH.
Github actions don't have git installed by default for example.
=> fix(hooks): reference full git path

extra/git/hooks.nix
When running devshell in a folder which is not a git repository, we face this error:
```
++ git rev-parse --show-toplevel
fatal: not a git repository (or any parent up to mount point /)
```
Solution is to abort git hook install if we are not in a git repository.
=> fix(hooks): do not install hooks if no git folder

modules/devshell.nix, nix/ansi.nix, nix/writeDefaultShellScript.nix
I wanted to use the full ansi color palette plus italic and underline in motd, plus I wanted to use it from TOML. This enables such usage through replacement strings. In the case of colors the replacement strings are just "{<color_number_here>}" while for bold, reset, underline and italic they are "{bold}", "{reset}", "{underline}" and "{italic}" respectively.
A toml example would be:
```toml
[devshell]
name = "ansi"
motd = """
{bold}{102}ANSI{reset}{102} - who doesn't like colors?{reset}
"""
```
=> Allow full 256 color ansi palette + italic, underline in toml and nix.

overlay.nix
As of 2fb6740996ccf01212f2efdf1dc2a9241a6acf57, `default.nix` changed its signature and the overlay was not updated for compatibility.
```
error: anonymous function at /nix/store/d4m6hpyv09n5k4x65mcxpsdxrdy0crfp-source/default.nix:1:1 called with unexpected argument 'pkgs'
at /nix/store/d4m6hpyv09n5k4x65mcxpsdxrdy0crfp-source/overlay.nix:4:14:
3| {
4|   devshell = import ./. { pkgs = final; };
|              ^
5| }
=> overlay.nix: fix

extra/services/postgres.nix
Add similar setting as nixos/modules/services/databases/postgresql.nix
to define custom parameters to `initdb`.
=> feat(services/postgres): add initdbArgs option

modules/devshell.nix
- allow a little more creativity in devshell naming:
- `numtide/devshell` -- `/` would have been illegal
- `Bitte Cells` -- ` ` would have been illegal
=> imp: sanitize devshell (derivation) name

modules/env.nix
This makes it easier to point an env var to a derivation path (eg: a
path to a config file that was generated with `nixpkgs.writeText`).
=> env: allow packages as values

docs/SUMMARY.md, docs/env.md, modules/devshell.nix
In some environments like CI, it doesn't make sense to show the menu
over and over again.
To avoid that noise, set DEVSHELL_NO_MOTD=1.
=> allow to disable the MOTD with an env var

extra/git/hooks.nix, tests/extra/git.hooks.nix
First, thanks for this convenient solution for managing git hooks.  It was very easy to get started rolling custom hooks (after [cribbing some plays from `digga`](https://github.com/divnix/digga/tree/396b04b62b885963c467aa8ade3c19398ade2d69/examples/devos/shell), to be sure :smiley: ). 
I use `git worktree` extensively, and it would be nice if `devshell` supported per-worktree hook definitions (if for no other reason than to more easily validate changes to git hooks made in a feature branch worktree). 
This pull request is a proposal to support per-worktree hooks via the use of shim scripts that can safely be installed to the shared hooks directory.  These shims read the real hook path from the `DEVSHELL_GIT_HOOKS_DIR` environment variable, whichs points to a store path containing the …
=> feat(hooks): draft/proposal: support multiple worktrees

docs/extending.md, extra/language/rust.nix
I've put the rust environment variables behind a flag, just in case some people might not want it.
I've removed the RUST_SRC_PKGS as I don't think anyone would be using the rust coming from nixpkgs as it is consistently 1 or 2 versions behind stable. Most people using rust would be using one of the multiple overlays.
I'll post once more when I have tested.
=> rust: add option for environment variables

docs/ci.md
Can't run `$(nix-build shell.nix)` because it's a directory.
Can't run `$(nix-build shell.nix)/entrypoint` because `$PRJ_ROOT` env var is missing.
Gotta do what these docs now say, to be able to successfully use devshell on CI systems.
=> docs: clarify CI usage

modules/devshell.nix
- can be used in downstream tooling for display
=> imp: add meta to the devshell module

extra/services/postgres.nix, tests/extra/services.postgres.nix
Calling initdb is pretty heavy and might not be needed by the user.
Maybe they are on another part of the monorepo. Or they are switching
between branches and don't care of using the DB in between. The point is
that we want to make this more lazy.
Introduce `start-postgres`, a script that setups the database before
starting postgres. Call that instead of postgres directly when stating
the database.
To restore the old behaviour, set
services.postgres.setupPostgresOnStartup = true;
=> BREAKING: extra/services/postgres: setup DB on demand

nix/mkNakedShell.nix
This issue was reported by @bzee:matrix.org. Apparently when running
`nix develop` on macOS, the system sets `/sbin/nologin` as the shell.
=> handle nologin on macOS

nix/mkNakedShell.nix
Fix devshell name presentation in pure shell https://github.com/sindresorhus/pure/blob/main/pure.zsh#L235
=> Preserve derivation name

.github/settings.yml, .github/workflows/goreleaser.yml, .github/workflows/nix.yml, bors.toml, devshell/cmd/enter.go, docs/book.toml, docs/getting_started.md, modules/modules.nix
Avoid issues when copy-pasting workflows and settings between repos.
=> repo: switch default branch to main

flake.nix
Fixes the following warnings:
```shell
❯ nix flake check
warning: flake output attribute 'defaultPackage' is deprecated; use 'packages.<system>.default' instead
warning: flake output attribute 'devShell' is deprecated; use 'devShells.<system>.default' instead
warning: flake output attribute 'defaultTemplate' is deprecated; use 'templates.default' instead
warning: flake output attribute 'overlay' is deprecated; use 'overlays.default' instead
```
=> fix: update deprecated default flake outputs

template/flake.nix
Updates the template.nix to use the default overlays, from https://github.com/numtide/devshell/commit/0c89450ba8935d9b1241e1ad42d4c870f123e142.
After running:
`nix develop` on a new project, `nix flake new -t "github:numtide/devshell" .`
I get the following error:
```
error: attribute 'overlay' missing
at /nix/store/a1nqfp20418q28hwks7dn86r1d45kjm7-source/demos/temporal/flake.nix:14:26:
13|
14|             overlays = [ devshell.overlay ];
|                          ^
15|           };
Did you mean overlays?
(use '--show-trace' to show detailed location information)
```
Hopefully this is enough to solve the issue.
=> Update the template.nix to use new default overlay

flake.lock, flake.nix
Make the flake externally extensible. Remove flake-utils to keep the dependency tree lean.
=> flake: use systems

README.md, docs/flake-app.md, flake.nix, modules/devshell.nix, modules/env.nix, tests/core/devshell.nix
I was poking at a `devshell` derivation in `nix repl` recently when I noticed its `flakeApp` attribute.  This is a cool feature!  I would love to be able to `nix run '.#my-devshell' -- <command>` and access commands from my devshell without having to first enter a `nix develop` sesson.  It looks like the `flakeApp` definition needs some updates to account for `devshell.nix` refactors; this PR is my attempt to apply those updates.  It also adds some convenience features, like a CLI option for specifying the project root path.
Have a few questions I'd like to resolve before removing "Draft" status from this PR:
1. Assuming you'd like to support `flakeApp`/`nix run`, where would you like me to document it?  I took a look at the files in `./docs` and nothing jumped out as an appropriate spot. …
=> feat(entrypoint): fixes/improvements to support `nix run` (devshell-as-flake-app)

modules/env.nix, tests/extra/language.c.nix
Revert "Prefer escapeShellArg over manual quoting"
This reverts commit a773f912ea85cdfa04a13070431abfc0c19ce79f.
Fixes #258.
=> Revert to manual quoting to make sure env variables can be used as part of other env variables when prefixing

extra/language/rust.nix
<details>
<summary>
```console
$ cargo build
error: linking with `cc` failed: exit status: 134
|
= note: LC_ALL="C" PATH="/nix...
...
= note: xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun
libc++abi: terminating with uncaught exception of type std::runtime_error: codesign_failed: 1
/nix/store/pz87iqygyl6gklpqlwd8bjs8sqd6hvl3-post-link-sign-hook: line 4: 74910 Abort trap: 6           CODESIGN_ALLOCATE=codesign_allocate /nix/store/ss3qicb0gzh00f87c6xs9nfdj92mad8k-sigtool-0.1.3/bin/codesign -f -s - "$linkerOutput"
```
</summary>
This is actually a mint cargo workspace with `lsp`, and many other "hello world" crates
```console
$ cargo build
error: linking with `cc` failed: exit status: 134 …
```
=> fix(extra/rust): xcbuild requires 2 paths to be exposed by env

templates/toml/devshell.toml
closes: https://github.com/numtide/devshell/issues/272
Thanks for this awesome library
=> fix `nix develop` shell in template

templates/toml/flake.nix, templates/toml/shell.nix
This allows `nix-shell` to be used from tools that have not yet been updated to support flakes (ex: https://github.com/arrterian/nix-env-selector)
=> Add `shell.nix` to flake template

templates/toml/flake.nix, templates/toml/shell.nix
When using `nix flake check`, we get a deprecated warning:
```
> nix flake check
warning: updating lock file '/tmp/devshell/templates/toml/flake.lock':
• Added input 'flake-compat':
'github:edolstra/flake-compat/0f9255e01c2351cc7d116c072cb317785dd33b33' (2023-10-04)
warning: flake output attribute 'devShell' is deprecated; use 'devShells.<system>.default' instead
```
This PR fixes this warning.
=> fix: use devShells.default on template flake

extra/language/perl.nix
Before that, the `PERL5LIB` was pointing to the specified libraries, but it was also ignoring all of their dependencies. After checking the [NixOS Wiki](https://nixos.wiki/wiki/Perl) guide for Perl, found out that it needs to use `makeFullPerlPath` instead.
=> perl: use makeFullPerlPath

modules/services.nix
Without quotes, if `$PWD` has spaces, then `my_service_name:start` would fail with something like `Process type 'stuff_after_a_space_char' does not exist in Procfile`.
=> services: Add quotes around $PRJ_ROOT to allow for paths with spaces

modules/devshell.nix
- outside of nix shells, e.g. when sourcing the env
respect the user's env preferences (e.g. starship)
=> fix: set PS1 in nix shells only

README.md, docs/src/flake-app.md, flake.nix, modules/devshell.nix, tests/core/devshell.nix
This makes all devshells compatible with `lib.getExe`, `nix run`and `nix bundle` by setting `meta.mainProgram` and creating an executable under `$out/bin/${meta.mainProgram}`
Also remove the now unnecessary flakeApp workaround from the docs and replace it with updated instructions.
My main motivation behind this is to create portable executable devshells via `nix bundle`.
For example, to bundle the devShell of devshell itself into a static executable:
```sh
nix bundle --bundler github:DavHau/nix-portable github:numtide/devshell#devShells.x86_64-linux.default
```
=> init compatibility with: nix bundle, nix run, lib.getExe

extra/language/hare.nix, tests/extra/language.hare.nix
The module, besides providing the Hare binary through
`devshell.packages`, exposes the following options:
1. `thirdPartyLibs`: add hare third-party libraries
(pkgs.hareThirdParty) to the HAREPATH environment variable.
2. `vendoredLibs`: add vendored libraries (any path on the project repo)
to HAREPATH.
3. `package`: set which `hare` package to use (defaults to `pkgs.hare`).
Regarding third-party libraries, the module also takes care of the ones
included on `propagatedBuildInputs`, by adding them to HAREPATH.
=> feat: add hare language support

modules/services.nix
This fixes a small issue with service groups (that I noticed a few months ago and forgot about myself).
If a service in a group encounters an `EXIT` the whole group stops, but the pidfile isn't cleaned up. To start the service again I would then have to call `service:stop` and `service:start`.  By trapping `EXIT`, we also cleanly stop the group and will clean up the pidfile.
I also added a check to see if the process is still running before killing is. Otherwise we'd get a print saying that the process doesn't exist:
```
09:16:06 system | ruby.1 started (pid=61570)
09:16:06 ruby.1 | main fn
09:16:06 system | ruby.1 stopped (rc=0)
/nix/store/kslx6csgb2bl13sp438vsx5kiq7s788c-example-services-start: line 11: kill: (61565) - No such process
```
A minimal reproduction of this issue can be …
=> Cleanly stop a service group if a service exits

extra/language/hare.nix
Also rework the function for including propagatedBuildInputs on it: The
new function ensures that the same path will not be repeated on the
environment variable.
The failure on MacOS is to be expected, since it's one of hare's `meta.badPlatforms`.
=> refactor(hare): ensure HAREPATH to be always set

tests/extra/language.hare.nix
As it was said on the TODO comment, this PR changes
`language.hare.thirdPartyLibs` to `pkgs.hareThirdParty.hare-png` to test the
inclusion of `propagatedBuildInputs` on `HAREPATH`.
The failure on MacOS is to be expected, since it's one of hare's `meta.badPlatforms`.
=> test(hare): check for propagatedBuildInputs on HAREPATH

extra/services/postgres.nix
right now `setup-postgres` and `start-postgres` are added to the user's dev shell, but there's little documentation about even the existence of these utilities. since they're non-standard utilities (that is, they aren't defined by `pkgs.postgresql`), it's non-ideal leaving them undocumented
this solution isn't *ideal* because the categories are subjective to my own categorization method, but this greatly improves ux
an even better solution would be to refactor the `commands` option to accept and attrset of `<name> = <command config>`, which would allow the user to respec the categories
=> feat(postgres): add `commands` configs

extra/language/c.nix
This env var fixes building `python-ldap` in a pdm python project when `openldap` is added to `language.c.libraries`, just like explained in https://github.com/numtide/devshell/issues/172#issuecomment-1094675420.
=> fix(c): add `LDFLAGS` automatically

.github/workflows/nix.yml, default.nix, docs/src/extending.md, flake-module.nix, modules/default.nix, modules/eval-args.nix, nix/importTOML.nix, templates/flake-parts/flake.nix
This PR factors out the construction of `specialArgs`, making those arguments available to flake module users as well as to users of `devshell.mkShell`.
Associated changes include:
1. Replacing uses of the name `extraModulesDir` with `extraModulesPath`, to harmonize with the name of the `specialArgs` entry,
2. Documentation of `extraModulesPath` usage, 
3. Demoing the use of `extraModulesPath` in the `flake-parts`-based flake template, and
4. Running the basic `nix develop <...> -c echo OK` sanity-check on all flake templates (thus testing that the `extraModulesPath` in the `flake-parts`-based template hasn't broken anything too badly).
Thank you!
=> Expose `specialArgs.modulesPath` and `specialArgs.extraModulesPath` to flake module consumers
